version: 2.1

jobs:
  "Build and Test Code":
    docker:
      - image: circleci/node:14.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
      - run: npm run testci
      - store_test_results:
          path: testreports
      - run: npm run codecov
  "Build and Push Docker Image":
    docker:
      - image: cimg/base:2021.10
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t jotajoti/jid-server .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p caches
            docker save -o caches/app.tar jotajoti/jid-server
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - caches/app.tar
      - run:
          name: Login and push to Docker Hub
          command: |
            echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push jotajoti/jid-server:latest

workflows:
  version: 2
  Build:
    jobs:
      - "Build and Test Code":
          filters:
            branches:
              ignore: master
  "Build and Publish":
    jobs:
      - "Build and Test Code":
          filters:
            branches:
              only: master
      - "Build and Push Docker Image":
          context: MainContext
          requires:
            - "Build and Test Code"
          filters:
            branches:
              only: master